# Generated by Django 4.1.6 on 2023-02-02 04:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Affiliation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('affiliation', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Character',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('hp_growth', models.PositiveSmallIntegerField()),
                ('str_growth', models.PositiveSmallIntegerField()),
                ('mag_growth', models.PositiveSmallIntegerField()),
                ('dex_growth', models.PositiveSmallIntegerField()),
                ('spd_growth', models.PositiveSmallIntegerField()),
                ('lck_growth', models.PositiveSmallIntegerField()),
                ('def_growth', models.PositiveSmallIntegerField()),
                ('res_growth', models.PositiveSmallIntegerField()),
                ('cha_growth', models.PositiveSmallIntegerField()),
                ('hp_limit', models.PositiveSmallIntegerField()),
                ('str_limit', models.PositiveSmallIntegerField()),
                ('mag_limit', models.PositiveSmallIntegerField()),
                ('dex_limit', models.PositiveSmallIntegerField()),
                ('spd_limit', models.PositiveSmallIntegerField()),
                ('lck_limit', models.PositiveSmallIntegerField()),
                ('def_limit', models.PositiveSmallIntegerField()),
                ('res_limit', models.PositiveSmallIntegerField()),
                ('cha_limit', models.PositiveSmallIntegerField()),
                ('affiliation', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='FE3HApp.affiliation')),
            ],
        ),
        migrations.CreateModel(
            name='Class_Weakness',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Gender',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gender', models.CharField(max_length=6)),
            ],
        ),
        migrations.CreateModel(
            name='Movement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('movement_type', models.CharField(max_length=20)),
                ('is_flying', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='SubjectLevel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject_level', models.CharField(max_length=2)),
            ],
        ),
        migrations.CreateModel(
            name='Weakness',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weakness', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='UnitClass',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=50)),
                ('grade', models.CharField(default='', max_length=10)),
                ('level_requirement', models.PositiveSmallIntegerField(default=0)),
                ('hp_growth', models.SmallIntegerField(default=0)),
                ('str_growth', models.SmallIntegerField(default=0)),
                ('mag_growth', models.SmallIntegerField(default=0)),
                ('dex_growth', models.SmallIntegerField(default=0)),
                ('spd_growth', models.SmallIntegerField(default=0)),
                ('lck_growth', models.SmallIntegerField(default=0)),
                ('def_growth', models.SmallIntegerField(default=0)),
                ('res_growth', models.SmallIntegerField(default=0)),
                ('cha_growth', models.SmallIntegerField(default=0)),
                ('hp_base', models.PositiveSmallIntegerField(default=0, null=True)),
                ('str_base', models.PositiveSmallIntegerField(default=0, null=True)),
                ('mag_base', models.PositiveSmallIntegerField(default=0, null=True)),
                ('dex_base', models.PositiveSmallIntegerField(default=0, null=True)),
                ('spd_base', models.PositiveSmallIntegerField(default=0, null=True)),
                ('lck_base', models.PositiveSmallIntegerField(default=0, null=True)),
                ('def_base', models.PositiveSmallIntegerField(default=0, null=True)),
                ('res_base', models.PositiveSmallIntegerField(default=0, null=True)),
                ('cha_base', models.PositiveSmallIntegerField(default=0, null=True)),
                ('prof_sword', models.CharField(default='', max_length=2, null=True)),
                ('prof_lance', models.CharField(default='', max_length=2, null=True)),
                ('prof_axe', models.CharField(default='', max_length=2, null=True)),
                ('prof_bow', models.CharField(default='', max_length=2, null=True)),
                ('prof_brawl', models.CharField(default='', max_length=2, null=True)),
                ('prof_reason', models.CharField(default='', max_length=2, null=True)),
                ('prof_faith', models.CharField(default='', max_length=2, null=True)),
                ('prof_authority', models.CharField(default='', max_length=2, null=True)),
                ('prof_armor', models.CharField(default='', max_length=2, null=True)),
                ('prof_riding', models.CharField(default='', max_length=2, null=True)),
                ('prof_flying', models.CharField(default='', max_length=2, null=True)),
                ('gender', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='FE3HApp.gender')),
                ('movement', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='FE3HApp.movement')),
                ('weakness', models.ManyToManyField(through='FE3HApp.Class_Weakness', to='FE3HApp.weakness')),
            ],
        ),
        migrations.CreateModel(
            name='CurrentUnit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.PositiveSmallIntegerField(default=0)),
                ('unit_hp', models.PositiveSmallIntegerField(default=0)),
                ('unit_str', models.PositiveSmallIntegerField(default=0)),
                ('unit_mag', models.PositiveSmallIntegerField(default=0)),
                ('unit_dex', models.PositiveSmallIntegerField(default=0)),
                ('unit_spd', models.PositiveSmallIntegerField(default=0)),
                ('unit_lck', models.PositiveSmallIntegerField(default=0)),
                ('unit_def', models.PositiveSmallIntegerField(default=0)),
                ('unit_res', models.PositiveSmallIntegerField(default=0)),
                ('unit_cha', models.PositiveSmallIntegerField(default=0)),
                ('prof_sword', models.CharField(default='E', max_length=2)),
                ('prof_lance', models.CharField(default='E', max_length=2)),
                ('prof_axe', models.CharField(default='E', max_length=2)),
                ('prof_bow', models.CharField(default='E', max_length=2)),
                ('prof_brawl', models.CharField(default='E', max_length=2)),
                ('prof_reason', models.CharField(default='E', max_length=2)),
                ('prof_faith', models.CharField(default='E', max_length=2)),
                ('prof_authority', models.CharField(default='E', max_length=2)),
                ('prof_armor', models.CharField(default='E', max_length=2)),
                ('prof_riding', models.CharField(default='E', max_length=2)),
                ('prof_flying', models.CharField(default='E', max_length=2)),
                ('character', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='FE3HApp.character')),
                ('unit_class', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='FE3HApp.unitclass')),
            ],
        ),
        migrations.AddField(
            model_name='class_weakness',
            name='class_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='FE3HApp.unitclass'),
        ),
        migrations.AddField(
            model_name='class_weakness',
            name='weakness_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='FE3HApp.weakness'),
        ),
        migrations.AddField(
            model_name='character',
            name='gender',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='FE3HApp.gender'),
        ),
        migrations.CreateModel(
            name='Battalion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('auth_requirement', models.CharField(max_length=2)),
                ('endurance', models.PositiveSmallIntegerField(default=0)),
                ('physical', models.SmallIntegerField(default=0)),
                ('magical', models.SmallIntegerField(default=0)),
                ('hit_rate', models.SmallIntegerField(default=0)),
                ('critical', models.SmallIntegerField(default=0)),
                ('avoidance', models.SmallIntegerField(default=0)),
                ('protection', models.SmallIntegerField(default=0)),
                ('resistance', models.SmallIntegerField(default=0)),
                ('charm', models.SmallIntegerField(default=0)),
                ('gambit', models.CharField(default='', max_length=50)),
                ('affiliation', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='FE3HApp.affiliation')),
                ('movement', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='FE3HApp.movement')),
            ],
        ),
    ]
