# Generated by Django 4.1.6 on 2023-02-09 01:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('FE3HApp', '0004_alter_currentunit_character'),
    ]

    operations = [
        migrations.AlterField(
            model_name='currentunit',
            name='character',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='FE3HApp.character'),
        ),
    ]
